-- =============================================================================
-- Migration V10: Allow ACCESSIBLE in seat.seat_type check constraint
-- Run on: movie_db
-- =============================================================================
-- SeatType.java gained ACCESSIBLE (wheelchair seating, auto-generated by
-- SeatService.generateSeatsForRoom), but the DB check constraint was never
-- updated — every room creation started failing with a raw constraint
-- violation (chk_seat_type) since the app tries to insert >=2 ACCESSIBLE
-- seats per room now.

ALTER TABLE seat DROP CONSTRAINT chk_seat_type;
ALTER TABLE seat ADD CONSTRAINT chk_seat_type
    CHECK (seat_type IN ('STANDARD', 'VIP', 'COUPLE', 'SWEETBOX', 'ACCESSIBLE'));
