-- V22: Align Premium Laser with the approved 11 x 14 reference layout.
-- Aisle placement is generated by the client from center_aisle metadata:
-- 2 seats + aisle + 8 seats + aisle + 2 seats. This also guarantees that the
-- last Couple row contains only complete two-position groups.

UPDATE room_configuration_template
SET default_rows = 11,
    default_positions_per_row = 14,
    description = 'Balanced premium room with 4K laser projection, Dolby 7.1, two side aisles and a rear Couple row'
WHERE template_code = 'PREMIUM_LASER';

-- Luxury Atmos retains its 10 x 14 density. The shared even-run aisle rule
-- prevents a single Couple position from being generated around the walkway.
UPDATE room_configuration_template
SET description = 'Low-density luxury room with 4K laser projection, Dolby Atmos, paired side aisles and a complete rear Couple row'
WHERE template_code = 'LUXURY_ATMOS';
