server:
  port: 8084

spring:
  application:
    name: user-service

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[spring.json.trusted.packages]": "*"
        "[spring.json.use.type.headers]": true
        "[spring.json.type.mapping]": "userRegistered:userservice.event.UserRegisteredEvent,userUpdated:userservice.event.UserUpdatedEvent"
    # Producer cần thiết để DefaultErrorHandler publish message thất bại sang DLT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dzlfgmtbc}
  api-key: ${CLOUDINARY_API_KEY:144287537763843}
  api-secret: ${CLOUDINARY_API_SECRET:7kJ1TfEb7kEAVArwaY5jq0ctvlA}

jwt:
  signerKey: 873bcf3b6023c6cfac735831cc01cbd59c6f64c2341050f12e5f0224d7edea62

eureka:
  instance:
    hostname: localhost
    instance-id: localhost:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}