CREATE DATABASE auth_db;
CREATE DATABASE movie_db;
CREATE DATABASE booking_db;
CREATE DATABASE payment_db;
CREATE DATABASE user_db;
CREATE DATABASE promotion_db;
CREATE DATABASE loyalty_db;
CREATE DATABASE workforce_db;
