version: '3.9'

services:

  # ===== FRONTEND =====
  admin-dashboard:
    build: ./client/admin-dashboard
    container_name: admin-dashboard
    ports:
      - "3000:3000"
    networks:
      - cinema-network

  customer-portal:
    build: ./client/customer-portal
    container_name: customer-portal
    ports:
      - "3001:3000"
    networks:
      - cinema-network

  # ===== MICROSERVICES DISCOVERY SERVER =====
  discovery-server:
    build: ./server/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - cinema-network

  # ===== BACKEND MICROSERVICES =====
  movie-service:
    build: ./server/movie-service
    container_name: movie-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/movie_catalog?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - mysql_db
      - discovery-server 
    networks:
      - cinema-network

  booking-service:
    build: ./server/booking-service
    container_name: booking-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456    
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - discovery-server 
    networks:
      - cinema-network

  payment-service:
    build: ./server/payment-service
    container_name: payment-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/database
      - SPRING_DATASOURCE_USERNAME=postgres  
      - SPRING_DATASOURCE_PASSWORD=123456    
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/ 
    depends_on:
      - postgres
      - discovery-server 
    networks:
      - cinema-network

  user-service:
    build: ./server/user-service
    container_name: user-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/database
      - SPRING_DATASOURCE_USERNAME=postgres  
      - SPRING_DATASOURCE_PASSWORD=123456   
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - discovery-server 
    networks:
      - cinema-network

  promotion-service:
    build: ./server/promotion-service
    container_name: promotion-service
    restart: on-failure 
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/movie_catalog?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - mysql_db
      - discovery-server 
    networks:
      - cinema-network

  notification-service:
    build: ./server/notification-service
    container_name: notification-service
    ports:
      - "8087:8087"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/ 
    depends_on:
      - discovery-server 
    networks:
      - cinema-network

  api-gateway:
    build: ./server/api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/ 
    depends_on:
      - discovery-server 
    networks:
      - cinema-network

  # ===== DATA LAYER =====
  # 🐘 PostgreSQL (Cho giao dịch, user)
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: database
    ports:
      - "5433:5432" 
    networks:
      - cinema-network

  # 🐬 MySQL (Cho danh mục phim, khuyến mãi)
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movie_catalog
    ports:
      - "3307:3306" 
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge