package movieservice.repository;

import movieservice.entity.Movie;
import movieservice.entity.MovieImage;
import movieservice.enums.MovieImageType;
import movieservice.enums.MovieStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "spring.sql.init.mode=never",
        "eureka.client.enabled=false",
        "spring.cloud.discovery.enabled=false"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
@Testcontainers(disabledWithoutDocker = true)
public class MovieImageRepositoryIntegrationTest {

    @Container
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16-alpine")
            .withDatabaseName("movie_service_test")
            .withUsername("test")
            .withPassword("test");

    @DynamicPropertySource
    static void datasourceProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
        registry.add("spring.datasource.username", POSTGRES::getUsername);
        registry.add("spring.datasource.password", POSTGRES::getPassword);
    }

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private MovieImageRepository movieImageRepository;

    private Movie testMovie;

    @BeforeEach
    void setUp() {
        movieImageRepository.deleteAll();

        testMovie = new Movie();
        testMovie.setOriginalTitle("Test Movie");
        testMovie.setOriginalLanguage("en");
        testMovie.setDurationMinutes(120);
        testMovie.setStatus(MovieStatus.DRAFT);
        testMovie = entityManager.persistAndFlush(testMovie);
    }

    @Test
    void save_ValidEnum_SavesSuccessfully() {
        MovieImage image = new MovieImage();
        image.setMovie(testMovie);
        image.setImageUrl("http://example.com/poster.png");
        image.setImageType(MovieImageType.POSTER);

        MovieImage saved = movieImageRepository.save(image);
        assertNotNull(saved.getImageId());
        assertEquals(MovieImageType.POSTER, saved.getImageType());
    }

    @Test
    void save_NativeQuery_LegacyMixedCase_UppercaseEnum() {
        // Native insert to bypass JPA enum mapping and simulate legacy invalid mixed-case
        entityManager.getEntityManager().createNativeQuery(
                "INSERT INTO movie_image (movie_id, image_url, image_type, created_at) VALUES (?, ?, ?, NOW())")
                .setParameter(1, testMovie.getMovieId())
                .setParameter(2, "http://example.com/backdrop.png")
                .setParameter(3, "BackDrop")
                .executeUpdate();

        // Let's run a migration script logic (normalize to uppercase)
        int updated = entityManager.getEntityManager().createNativeQuery(
                "UPDATE movie_image SET image_type = UPPER(TRIM(image_type))")
                .executeUpdate();

        assertEquals(1, updated);

        // Verify we can now load it via JPA as Enum
        entityManager.clear();
        var images = movieImageRepository.findAll();
        assertEquals(1, images.size());
        assertEquals(MovieImageType.BACKDROP, images.get(0).getImageType());
    }

    @Test
    void save_NativeQuery_CheckConstraint_ThrowsException() {
        // Since schema is generated by Hibernate, we manually add the check constraint
        entityManager.getEntityManager().createNativeQuery(
                "ALTER TABLE movie_image ADD CONSTRAINT chk_image_type CHECK (image_type IN ('POSTER', 'BACKDROP', 'STILL', 'PROMOTIONAL', 'LOGO'))")
                .executeUpdate();

        // Attempting to insert an invalid type directly into DB should fail
        assertThrows(Exception.class, () -> {
            entityManager.getEntityManager().createNativeQuery(
                    "INSERT INTO movie_image (movie_id, image_url, image_type, created_at) VALUES (?, ?, ?, NOW())")
                    .setParameter(1, testMovie.getMovieId())
                    .setParameter(2, "http://example.com/invalid.png")
                    .setParameter(3, "UNKNOWN")
                    .executeUpdate();
        });
    }
}
