package movieservice.repository;

import movieservice.entity.Movie;
import movieservice.entity.MovieImage;
import movieservice.enums.MovieImageType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.ActiveProfiles;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@ActiveProfiles("test")
public class MovieImageRepositoryIntegrationTest {

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private MovieImageRepository movieImageRepository;

    private Movie testMovie;

    @BeforeEach
    void setUp() {
        testMovie = new Movie();
        testMovie.setOriginalTitle("Test Movie");
        testMovie.setOriginalLanguage("en");
        testMovie.setDurationMinutes((short) 120);
        testMovie = entityManager.persistAndFlush(testMovie);
    }

    @Test
    void save_ValidEnum_SavesSuccessfully() {
        MovieImage image = new MovieImage();
        image.setMovie(testMovie);
        image.setImageUrl("http://example.com/poster.png");
        image.setImageType(MovieImageType.POSTER);

        MovieImage saved = movieImageRepository.save(image);
        assertNotNull(saved.getImageId());
        assertEquals(MovieImageType.POSTER, saved.getImageType());
    }

    @Test
    void save_NativeQuery_LegacyMixedCase_UppercaseEnum() {
        // Native insert to bypass JPA enum mapping and simulate legacy invalid mixed-case
        // Note: H2 allows this for string columns. But if mapped to enum, JPA might fail to load it later.
        entityManager.getEntityManager().createNativeQuery(
                "INSERT INTO movie_image (movie_id, image_url, image_type) VALUES (?, ?, ?)")
                .setParameter(1, testMovie.getMovieId())
                .setParameter(2, "http://example.com/backdrop.png")
                .setParameter(3, "BackDrop")
                .executeUpdate();

        // Let's run a migration script logic (normalize to uppercase)
        int updated = entityManager.getEntityManager().createNativeQuery(
                "UPDATE movie_image SET image_type = UPPER(TRIM(image_type))")
                .executeUpdate();
        
        assertEquals(1, updated);
        
        // Verify we can now load it via JPA as Enum
        entityManager.clear();
        var images = movieImageRepository.findAll();
        assertEquals(1, images.size());
        assertEquals(MovieImageType.BACKDROP, images.get(0).getImageType());
    }

    @Test
    void save_NativeQuery_CheckConstraint_ThrowsException() {
        // Since H2 schema is generated by Hibernate and doesn't include our custom CHECK constraint
        // from the PostgreSQL init script, we manually add it for this test.
        entityManager.getEntityManager().createNativeQuery(
                "ALTER TABLE movie_image ADD CONSTRAINT chk_image_type CHECK (image_type IN ('POSTER', 'BACKDROP', 'STILL', 'PROMOTIONAL', 'LOGO'))")
                .executeUpdate();

        // Attempting to insert an invalid type directly into DB should fail
        assertThrows(Exception.class, () -> {
            entityManager.getEntityManager().createNativeQuery(
                    "INSERT INTO movie_image (movie_id, image_url, image_type) VALUES (?, ?, ?)")
                    .setParameter(1, testMovie.getMovieId())
                    .setParameter(2, "http://example.com/invalid.png")
                    .setParameter(3, "UNKNOWN")
                    .executeUpdate();
        });
    }
}
