server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/**, /api/cinemas/**, /api/shows/**, /api/showtimes/**, /api/cinema-rooms/**, /api/cinema-room-master-data, /api/cinema-clusters/**, /api/seats/**, /api/schedules/**, /api/genres/**, /api/age-ratings/**, /api/screening-formats/**, /api/companies/**, /api/persons/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**, /api/tickets/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/employees/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /api/permissions/**, /api/roles/**, /api/accounts/**

eureka:
  instance:
    hostname: localhost
    instance-id: localhost:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
