server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS 
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: movie-service
          uri: lb://movie-service 
          predicates:
            - Path=/api/movies/**, /api/cinemas/**, /api/shows/** - id: booking-service
          uri: lb://booking-service 
          predicates:
            - Path=/api/bookings/**, /api/tickets/**
            
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /api/permissions/**, /api/roles/**, /api/accounts/**
            
eureka:
  instance:
    hostname: localhost
    instance-id: localhost:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}