package movieservice.enums;

public enum GenerationSkipReason {
    INVALID_MOVIE,
    MOVIE_NOT_AVAILABLE,
    NO_COMPATIBLE_FORMAT,
    NO_ELIGIBLE_ROOM,
    OUTSIDE_OPERATING_HOURS,
    CROSS_MIDNIGHT_NOT_SUPPORTED,
    CLEANUP_BUFFER_CONFLICT,
    EXISTING_SHOWTIME_CONFLICT,
    DATABASE_OVERLAP_CONFLICT,
    MAXIMUM_ROOM_SHARE_REACHED,
    MAX_DAILY_SHOWS_PER_MOVIE_REACHED,
    MISSING_DEMAND_PROFILE,
    NO_AVAILABLE_TIME_SLOT
}
