CREATE TABLE auth_token
(
    token_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jwt_id     VARCHAR(100)                            NOT NULL,
    token_type VARCHAR(20),
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    issued_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_revoked BOOLEAN                                 NOT NULL,
    created_ip INET,
    user_agent VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_auth_token PRIMARY KEY (token_id)
);

CREATE TABLE auth_token_account
(
    auth_token_token_id BIGINT      NOT NULL,
    account_account_id  VARCHAR(36) NOT NULL
);

ALTER TABLE auth_token
    ADD CONSTRAINT uc_auth_token_jwt UNIQUE (jwt_id);

ALTER TABLE auth_token_account
    ADD CONSTRAINT fk_auttokacc_on_account FOREIGN KEY (account_account_id) REFERENCES account (account_id);

ALTER TABLE auth_token_account
    ADD CONSTRAINT fk_auttokacc_on_auth_token FOREIGN KEY (auth_token_token_id) REFERENCES auth_token (token_id);