CREATE TABLE password_reset
(
    reset_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id VARCHAR(36)                             NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    purpose    VARCHAR(30),
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used_at    TIMESTAMP WITHOUT TIME ZONE,
    is_used    BOOLEAN                                 NOT NULL,
    created_ip INET,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_password_reset PRIMARY KEY (reset_id)
);

ALTER TABLE password_reset
    ADD CONSTRAINT uc_password_reset_token UNIQUE (token);

ALTER TABLE password_reset
    ADD CONSTRAINT FK_PASSWORD_RESET_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (account_id);
CREATE TABLE password_reset
(
    reset_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id VARCHAR(36)                             NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    purpose    VARCHAR(30),
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used_at    TIMESTAMP WITHOUT TIME ZONE,
    is_used    BOOLEAN                                 NOT NULL,
    created_ip INET,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_password_reset PRIMARY KEY (reset_id)
);

ALTER TABLE password_reset
    ADD CONSTRAINT uc_password_reset_token UNIQUE (token);

ALTER TABLE password_reset
    ADD CONSTRAINT FK_PASSWORD_RESET_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (account_id);

-- Upgrade for databases created before activation and password recovery were separated.
-- NULL is kept temporarily for backward compatibility with existing activation tokens.
ALTER TABLE password_reset
    ADD COLUMN IF NOT EXISTS purpose VARCHAR(30);
