package movieservice.exception;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;
import movie.theater.common.exception.BaseErrorCode;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
@AllArgsConstructor
public enum MovieErrorCode implements BaseErrorCode {

        MOVIE_TYPE_NOT_FOUND(2001, "Movie genre not found with the provided ID.", HttpStatus.NOT_FOUND),
        MOVIE_NOT_FOUND(2002, "Movie not found.", HttpStatus.NOT_FOUND),

        CINEMA_ROOM_NOT_FOUND(2003, "Cinema room does not exist.", HttpStatus.NOT_FOUND),
        CINEMA_ROOM_NAME_EXISTED(2004, "Room name already exists!!!", HttpStatus.CONFLICT),

        MOVIE_TYPE_NAME_EXISTED(2005, "Movie type name already exists!!!", HttpStatus.CONFLICT),

        INVALID_SHOWTIME(2006,
                        "Invalid showtime! The cinema only operates from 8:00 AM to 11:00 PM",
                        HttpStatus.BAD_REQUEST),

        SHOWTIME_CONFLICT_IN_REQUEST(2007,
                        "Conflict: A movie schedule already exists in this room",
                        HttpStatus.CONFLICT),

        INVALID_SHOWDATE(2008,
                        "Invalid showdate! Showtimes must be scheduled at least 3 days in advance from today.",
                        HttpStatus.BAD_REQUEST),

        SHOWTIME_CONFLICT_IN_DATABASE(2009,
                        "The room has been booked for another showtime.",
                        HttpStatus.CONFLICT),
        UPLOAD_IMAGE_FAILED(5001, "Failed to upload image to Cloudinary", HttpStatus.INTERNAL_SERVER_ERROR),
        INVALID_IMAGE_FILE(5002, "Invalid image file. Please upload a JPG, PNG, or WebP image up to 5MB.",
                        HttpStatus.BAD_REQUEST),

        INTERNAL_SERVER_ERROR(5000,
                        "Internal server error",
                        HttpStatus.INTERNAL_SERVER_ERROR),

        GENRE_NOT_FOUND(2010, "Movie genre not found.", HttpStatus.NOT_FOUND),
        ACTIVE_SHOWTIMES_EXIST(2011, "Cannot delete movie because it still has upcoming showtimes.",
                        HttpStatus.CONFLICT),

        SEAT_NOT_FOUND(2012, "Seat not found.", HttpStatus.NOT_FOUND),
        INVALID_SEAT_STATUS(4001, "Invalid seat status", HttpStatus.BAD_REQUEST),

        MOVIE_ALREADY_EXISTS(2014, "A movie with this Vietnamese title and format already exists.",
                        HttpStatus.CONFLICT),

        SHOWTIME_NOT_FOUND(2015, "Showtime not found.", HttpStatus.NOT_FOUND),

        AGE_RATING_NOT_FOUND(2016, "Age rating not found.", HttpStatus.NOT_FOUND),
        COMPANY_NOT_FOUND(2017, "Production company not found.", HttpStatus.NOT_FOUND),
        FORMAT_NOT_FOUND(2018, "Screening format not found.", HttpStatus.NOT_FOUND),
        PERSON_NOT_FOUND(2019, "Person (cast member) not found.", HttpStatus.NOT_FOUND),
        INVALID_STATUS_TRANSITION(2020, "This status transition is not allowed.", HttpStatus.BAD_REQUEST),
        TMDB_MOVIE_ALREADY_EXISTS(2021, "This TMDB movie has already been imported.", HttpStatus.CONFLICT),
        TMDB_API_ERROR(2022, "Failed to connect to TMDB API. Check your API key or network.", HttpStatus.BAD_GATEWAY),

        CLUSTER_NOT_FOUND(2023, "Cinema cluster not found.", HttpStatus.NOT_FOUND),
        CLUSTER_HAS_ROOMS(2024, "Cannot delete cluster that still has cinema rooms.", HttpStatus.CONFLICT),
        INVALID_CLUSTER_STATUS(2025, "Invalid status. Accepted values: DRAFT, PENDING_REVIEW, ACTIVE, INACTIVE",
                        HttpStatus.BAD_REQUEST),
        CLUSTER_INVALID_TRANSITION(2026,
                        "Invalid status transition. Check the cluster's current status and use the correct workflow endpoint.",
                        HttpStatus.BAD_REQUEST),
        CLUSTER_NAME_EXISTED(2027, "Cluster name already exists!!!", HttpStatus.CONFLICT),

        CINEMA_ROOM_HAS_SHOWTIMES(2028, "Cannot delete cinema room that still has showtimes.", HttpStatus.CONFLICT),
        CLUSTER_NOT_ACTIVE(2029, "Cannot create a room in a cluster that is not ACTIVE.", HttpStatus.BAD_REQUEST),

        SEAT_ROW_LIMIT_EXCEEDED(2030,
                        "Seat quantity for this room type produces too many rows to lay out safely.",
                        HttpStatus.BAD_REQUEST),

        DUPLICATE_TRANSLATION_LANGUAGE(2034,
                        "Duplicate languageCode found in translations request.",
                        HttpStatus.BAD_REQUEST),

        DUPLICATE_CAST_ENTRY(2035,
                        "Duplicate (personId, roleType) combination found in cast request.",
                        HttpStatus.BAD_REQUEST),

        BULK_SHOWTIME_REQUEST_TOO_LARGE(2037,
                        "Bulk showtime request exceeds the allowed date range or candidate limit.",
                        HttpStatus.BAD_REQUEST),

        MISSING_RUNTIME(2038,
                        "TMDB did not provide a runtime for this movie. Provide confirmedRuntimeMinutes to import.",
                        HttpStatus.BAD_REQUEST),

        UNRESOLVED_GENRE_MAPPING(2039,
                        "One or more TMDB genres are unmapped. Map, create as pending review, or ignore them before importing.",
                        HttpStatus.BAD_REQUEST),

        GENRE_PENDING_REVIEW(2040,
                        "Cannot submit for review while the movie has a genre still PENDING_REVIEW.",
                        HttpStatus.BAD_REQUEST),

        MOVIE_NOT_READY_FOR_REVIEW(2041, "Movie is not ready for review.", HttpStatus.BAD_REQUEST),
        MOVIE_NOT_READY_FOR_APPROVAL(2042, "Movie is not ready for approval.", HttpStatus.BAD_REQUEST),
        MOVIE_NOT_READY_FOR_RELEASE(2043, "Movie is not ready for release.", HttpStatus.BAD_REQUEST),

        // ── Cinema Room creation wizard / seat layout versioning ────────────────

        ROOM_LAYOUT_NOT_FOUND(2044, "Room layout version not found.", HttpStatus.NOT_FOUND),
        ROOM_LAYOUT_INVALID_TRANSITION(2045,
                        "Invalid layout status transition. Check the layout's current status and use the correct workflow endpoint.",
                        HttpStatus.BAD_REQUEST),
        ROOM_LAYOUT_NOT_EDITABLE(2046,
                        "Only a DRAFT layout can be edited. Clone this version to create a new editable draft.",
                        HttpStatus.BAD_REQUEST),
        ROOM_LAYOUT_POSITION_DUPLICATE_COORDINATE(2047,
                        "Two or more positions share the same row/column coordinate.", HttpStatus.BAD_REQUEST),
        ROOM_LAYOUT_POSITION_DUPLICATE_SEAT_CODE(2048,
                        "Two or more seat positions share the same seat code.", HttpStatus.BAD_REQUEST),
        ROOM_LAYOUT_COUPLE_GROUP_INVALID(2049,
                        "Each Couple group must contain exactly two adjacent seat positions in the same row.",
                        HttpStatus.BAD_REQUEST),
        ROOM_LAYOUT_EMPTY(2050, "Cannot submit a layout with no positions.", HttpStatus.BAD_REQUEST),
        ROOM_LAYOUT_HAS_FUTURE_SHOWTIMES(2051,
                        "Cannot activate this layout version: the room has upcoming scheduled/on-sale showtimes on the current active layout.",
                        HttpStatus.CONFLICT),
        ROOM_SCREEN_EXCEEDS_ROOM_DIMENSIONS(2052,
                        "Screen width/height cannot exceed the room's width/clear height.", HttpStatus.BAD_REQUEST),
        AUDITORIUM_CLASS_NOT_FOUND(2053, "Auditorium class not found or inactive.", HttpStatus.NOT_FOUND),
        PROJECTION_TECHNOLOGY_NOT_FOUND(2054, "Projection technology not found or inactive.", HttpStatus.NOT_FOUND),
        RESOLUTION_NOT_FOUND(2055, "Resolution not found or inactive.", HttpStatus.NOT_FOUND),
        AUDIO_FORMAT_NOT_FOUND(2056, "Audio format not found or inactive.", HttpStatus.NOT_FOUND),
        ROOM_INVALID_TRANSITION(2057,
                        "Invalid room status transition. Check the room's current status and use the correct workflow endpoint.",
                        HttpStatus.BAD_REQUEST),
        ROOM_CODE_ALREADY_EXISTS(2058, "Room code already exists in this cluster!!!", HttpStatus.CONFLICT),
        ROOM_NOT_DRAFT(2059,
                        "Room details can only be edited while the room is DRAFT.", HttpStatus.BAD_REQUEST),
        ROOM_LAYOUT_POSITION_FIELDS_INVALID(2060,
                        "AISLE/EXIT/EMPTY_SPACE positions must not carry seat fields; SEAT positions must.",
                        HttpStatus.BAD_REQUEST),
        ROOM_CODE_REQUIRED(2061, "Room code is required when creating a room through the wizard.",
                        HttpStatus.BAD_REQUEST),
        ROOM_DIMENSION_INVALID(2062, "Room length/width/clear height must be greater than 0.",
                        HttpStatus.BAD_REQUEST),
        ROOM_LAYOUT_EXCEEDS_ROOM_ENVELOPE(2063,
                        "The seat layout exceeds the room capacity envelope derived from area, volume, seat width, row pitch, or screen clearance.",
                        HttpStatus.BAD_REQUEST),
        ROOM_PRESENTATION_FORMAT_REQUIRED(2064,
                        "At least one presentation format (2D or 3D) must be supported.",
                        HttpStatus.BAD_REQUEST),
        CLUSTER_CODE_EXISTED(2065, "Cluster code already exists.", HttpStatus.CONFLICT),
        CLUSTER_CODE_IMMUTABLE(2066, "Cluster code cannot be changed after the cluster leaves DRAFT.",
                        HttpStatus.BAD_REQUEST),
        CLUSTER_OPERATING_HOURS_INVALID(2067,
                        "Operating hours must contain each day exactly once and use valid local times.",
                        HttpStatus.BAD_REQUEST),
        CLUSTER_TIMEZONE_INVALID(2068, "Timezone must be a valid IANA timezone identifier.", HttpStatus.BAD_REQUEST),

        // ── Movie content/exhibition lifecycle separation (MOV-LC-04/06) ────────

        MOVIE_NOT_EDITABLE(2069,
                        "Only a DRAFT movie can be edited directly. Start a revision first if changes were requested.",
                        HttpStatus.CONFLICT),
        MOVIE_HAS_ACTIVE_AVAILABILITY(2071,
                        "Cannot archive a movie that still has a non-closed release plan. Close it first.",
                        HttpStatus.CONFLICT),

        AVAILABILITY_NOT_FOUND(2072, "Movie availability not found.", HttpStatus.NOT_FOUND),
        AVAILABILITY_INVALID_TRANSITION(2073,
                        "Invalid availability status transition. Check the current status and use the correct command.",
                        HttpStatus.CONFLICT),
        AVAILABILITY_MOVIE_NOT_APPROVED(2075,
                        "An availability window can only be created for a movie whose content status is APPROVED.",
                        HttpStatus.CONFLICT),
        AVAILABILITY_CLUSTER_NOT_ACTIVE(2076,
                        "Cannot create an availability window at a cluster that is not ACTIVE.",
                        HttpStatus.BAD_REQUEST),
        AVAILABILITY_DATE_RANGE_INVALID(2077,
                        "showingEndDate must be on or after showingStartDate.", HttpStatus.BAD_REQUEST),
        AVAILABILITY_WINDOW_ALREADY_EXISTS(2078,
                        "An availability window for this movie, cluster and showingStartDate already exists.",
                        HttpStatus.CONFLICT),
        AVAILABILITY_NOT_EDITABLE(2079,
                        "Only a PLANNED or CHANGES_REQUESTED release plan can be edited directly.", HttpStatus.CONFLICT),

        CLUSTER_SELF_APPROVAL_FORBIDDEN(2080,
                        "You cannot approve or reject a cluster you created yourself. Another admin must review it.",
                        HttpStatus.FORBIDDEN),
        CLUSTER_NOT_OWNER(2081,
                        "Only the cluster's creator or an admin can submit it for review.", HttpStatus.FORBIDDEN),

        CINEMA_ROOM_DELETE_NOT_ALLOWED(2082,
                        "Only an unused DRAFT cinema room that has never entered an operational workflow can be permanently deleted.",
                        HttpStatus.CONFLICT),
        CINEMA_ROOM_DELETE_FORBIDDEN(2083,
                        "Only an ADMIN or the employee who created this draft cinema room can permanently delete it.",
                        HttpStatus.FORBIDDEN),

        TMDB_IMAGE_NOT_FOUND(2084,
                        "One or more selected images are no longer available from TMDB for this title.",
                        HttpStatus.BAD_REQUEST),
        TMDB_IMAGE_ALREADY_IMPORTED(2085,
                        "This TMDB image has already been imported for this movie.", HttpStatus.CONFLICT),
        MOVIE_IMAGE_TYPE_LIMIT_EXCEEDED(2086,
                        "At most 1 poster and 1 backdrop can be imported per request; stills are capped by the configured maximum.",
                        HttpStatus.BAD_REQUEST),
        MOVIE_IMAGE_NOT_FOUND(2087, "Movie image not found.", HttpStatus.NOT_FOUND),

        CLUSTER_DELETE_NOT_ALLOWED(2088,
                        "Only an unused DRAFT cinema cluster that has never entered review or operation can be permanently deleted.",
                        HttpStatus.CONFLICT),
        CLUSTER_DELETE_FORBIDDEN(2089,
                        "Only an ADMIN can permanently delete an unused cinema cluster draft.",
                        HttpStatus.FORBIDDEN),
        CLUSTER_HAS_MOVIE_AVAILABILITY(2090,
                        "Cannot permanently delete a cinema cluster referenced by movie availability history.",
                        HttpStatus.CONFLICT),

        GENRE_NOT_PENDING_REVIEW(2091,
                        "Only a genre in PENDING_REVIEW status can be approved.",
                        HttpStatus.CONFLICT),

        PERSON_NAME_ALREADY_EXISTS(2092,
                        "A person with this name already exists. Search for them instead of creating a duplicate.",
                        HttpStatus.CONFLICT),
        PERSON_STILL_REFERENCED(2093,
                        "Cannot delete a person who is still credited as cast/crew on one or more movies.",
                        HttpStatus.CONFLICT),

        AUTO_SHOWTIME_POLICY_NOT_FOUND(2094,
                        "No active showtime allocation policy was found.", HttpStatus.NOT_FOUND),
        INVALID_GENERATION_RANGE(2095,
                        "The requested date range is outside the configured scheduling horizon.", HttpStatus.BAD_REQUEST),
        GENERATION_RUN_NOT_FOUND(2096,
                        "Auto showtime generation run was not found.", HttpStatus.NOT_FOUND),
        AUTO_SHOWTIME_MOVIE_NOT_APPROVED(2097,
                        "Auto showtime generation requires every selected movie to be APPROVED.", HttpStatus.CONFLICT),
        AUTO_SHOWTIME_NO_SCHEDULABLE_AVAILABILITY(2098,
                        "No selected movie has an APPROVED or OPEN release plan for the selected cluster and date range.",
                        HttpStatus.BAD_REQUEST),
        AUTO_SHOWTIME_NO_ELIGIBLE_CANDIDATE(2099,
                        "No eligible showtime candidate exists. Check cluster operating hours, active rooms, and room format capabilities.",
                        HttpStatus.BAD_REQUEST),
        AUTO_SHOWTIME_SELECTED_MOVIE_NOT_ELIGIBLE(2100,
                        "Every selected movie must have at least one eligible showtime candidate.",
                        HttpStatus.BAD_REQUEST),
        AUTO_SHOWTIME_CLUSTER_NOT_SCHEDULABLE(2101,
                        "Every selected cinema cluster must have at least one ACTIVE room with an ACTIVE sellable seat layout.",
                        HttpStatus.BAD_REQUEST),
        SHOWTIME_ROOM_NOT_SCHEDULABLE(2102,
                        "The selected room must belong to an ACTIVE cinema cluster and have an ACTIVE sellable seat layout.",
                        HttpStatus.BAD_REQUEST),
        SCHEDULE_PLAN_NOT_FOUND(2103, "Schedule plan was not found.", HttpStatus.NOT_FOUND),
        SCHEDULE_PLAN_INVALID_TRANSITION(2104,
                        "The requested schedule plan transition is not allowed.", HttpStatus.CONFLICT),
        SCHEDULE_PLAN_PUBLISH_CONFLICT(2105,
                        "Schedule plan cannot be published because one or more slots are no longer valid.",
                        HttpStatus.CONFLICT),
        SCHEDULE_PLAN_ELIGIBILITY_CHANGED(2106,
                        "Schedule plan rights, classification, or availability eligibility has changed.",
                        HttpStatus.CONFLICT),
        SHOWTIME_CANCELLATION_REASON_REQUIRED(2107,
                        "A cancellation reason is required when cancelling a showtime.",
                        HttpStatus.BAD_REQUEST),
        SHOWTIME_TERMINAL_STATUS(2108,
                        "A cancelled or completed showtime cannot be transitioned to another status.",
                        HttpStatus.CONFLICT),
        AUTO_SHOWTIME_REPLAN_NOT_SUPPORTED(2109,
                        "Rolling replanning is not implemented yet. Submit a fresh generation run instead.",
                        HttpStatus.BAD_REQUEST),
        AUTO_SHOWTIME_INVALID_SCREENING_VERSION_SELECTION(2151,
                        "A screening-version override is invalid, inactive, expired, or does not belong to the selected movie.",
                        HttpStatus.BAD_REQUEST),

        // ── Showtime allocation policy admin CRUD ──────────────────────────────

        ALLOCATION_POLICY_NOT_FOUND(2110,
                        "Showtime allocation policy was not found.", HttpStatus.NOT_FOUND),
        ALLOCATION_POLICY_CODE_DUPLICATE(2111,
                        "A policy with this policy_code already exists.", HttpStatus.CONFLICT),

        ROOM_FORMAT_MANAGED_AUTOMATICALLY(2112,
                        "This format is derived automatically from the room's supports2d/supports3d/"
                                        + "presentationSystem settings — edit those instead of toggling it directly.",
                        HttpStatus.CONFLICT),

        CINEMA_ROOM_STATUS_TRANSITION_INVALID(2113,
                        "Invalid cinema room status transition. Wizard states (DRAFT/PENDING_APPROVAL/APPROVED) are "
                                        + "managed by the layout approval workflow, MAINTENANCE/TEMPORARILY_UNAVAILABLE by "
                                        + "report/resolve maintenance, and RETIRED is a permanent, one-way transition only "
                                        + "available through the retire endpoint.",
                        HttpStatus.CONFLICT),
        CINEMA_ROOM_HAS_FUTURE_SHOWTIMES(2114,
                        "Cannot retire a cinema room that still has scheduled or on-sale showtimes.",
                        HttpStatus.CONFLICT),

        // ── Cinema cluster demand profile admin CRUD (removes the V33 backfill-migration
        //    stopgap: profiles are now created/edited through this endpoint, and a default
        //    is auto-created on cluster approval instead of relying on a one-time migration) ──

        CLUSTER_DEMAND_PROFILE_NOT_FOUND(2115,
                        "This cinema cluster does not have a demand profile configured yet.",
                        HttpStatus.NOT_FOUND),

        SCREENING_VERSION_NOT_FOUND(2116,
                        "Movie screening version was not found.", HttpStatus.NOT_FOUND),
        SCREENING_VERSION_DUPLICATE(2117,
                        "This movie already has the same presentation format, audio format, audio language and subtitle language version.",
                        HttpStatus.CONFLICT),
        SCREENING_VERSION_DATE_RANGE_INVALID(2118,
                        "effectiveTo must be on or after effectiveFrom.", HttpStatus.BAD_REQUEST),
        SCREENING_VERSION_FORMAT_NOT_CONFIGURED(2119,
                        "The selected screening format is not configured on this movie.",
                        HttpStatus.BAD_REQUEST),
        SCREENING_VERSION_REFERENCED_IMMUTABLE(2120,
                        "A screening version referenced by a schedule, showtime or theatrical license cannot be rewritten. Deactivate it and create a replacement version.",
                        HttpStatus.CONFLICT),
        SCREENING_FORMAT_AUDIO_CODE_INVALID(2121,
                        "Audio technologies such as Dolby Atmos must be configured as an audio format, not as a presentation format.",
                        HttpStatus.BAD_REQUEST),

        SHOWTIME_INVENTORY_NOT_MATERIALIZED(2122,
                        "Seat inventory has not been materialized for this showtime.",
                        HttpStatus.CONFLICT),
        SHOWTIME_ACTIVE_LAYOUT_NOT_FOUND(2123,
                        "The showtime room does not have an active sellable layout.",
                        HttpStatus.CONFLICT),
        SHOWTIME_LAYOUT_SEAT_MISMATCH(2124,
                        "The active room layout and master seat inventory are out of sync.",
                        HttpStatus.CONFLICT),
        SEAT_HOLD_SELECTION_INVALID(2125,
                        "The seat selection is empty, contains duplicate seats, or includes seats outside this showtime.",
                        HttpStatus.BAD_REQUEST),
        SEAT_NOT_AVAILABLE(2126,
                        "One or more selected seats are no longer available. Refresh the seat map and choose again.",
                        HttpStatus.CONFLICT),
        SEAT_HOLD_IDEMPOTENCY_KEY_REQUIRED(2127,
                        "A valid Idempotency-Key header is required when holding seats.",
                        HttpStatus.BAD_REQUEST),
        SEAT_HOLD_IDEMPOTENCY_CONFLICT(2128,
                        "This Idempotency-Key was already used with a different seat selection.",
                        HttpStatus.CONFLICT),
        SEAT_HOLD_OWNER_REQUIRED(2129,
                        "An authenticated account is required to hold seats.",
                        HttpStatus.UNAUTHORIZED),
        SEAT_HOLD_EXPIRED(2130,
                        "This seat hold has expired. Refresh availability and submit a new request.",
                        HttpStatus.CONFLICT),
        SHOWTIME_PRICE_NOT_CONFIGURED(2131,
                        "Ticket price is not configured. Set a Standard-seat base price for the showtime or configure positive prices on the room's active seats.",
                        HttpStatus.CONFLICT),
        SHOWTIME_PRICE_LOCKED(2132,
                        "Ticket prices can only be changed while the showtime is SCHEDULED and has not opened for sales.",
                        HttpStatus.CONFLICT),
        PRICE_BOOK_NOT_FOUND(2133,
                        "Price book was not found.", HttpStatus.NOT_FOUND),
        PRICE_BOOK_CODE_DUPLICATE(2134,
                        "A price book with this code already exists.", HttpStatus.CONFLICT),
        PRICE_BOOK_DATE_RANGE_INVALID(2135,
                        "Price book validTo must be on or after validFrom.", HttpStatus.BAD_REQUEST),
        PRICE_BOOK_REQUIRES_RATE(2136,
                        "A price book must contain at least one active rate before it can be activated.",
                        HttpStatus.CONFLICT),
        PRICE_RATE_TIME_RANGE_INVALID(2137,
                        "A rate card time range cannot have the same start and end time.",
                        HttpStatus.BAD_REQUEST),
        PRICE_BOOK_ARCHIVED(2138,
                        "An archived price book cannot be modified or activated.",
                        HttpStatus.CONFLICT),
        SCHEDULE_PLAN_REVIEW_BLOCKED(2139,
                        "Schedule plan cannot be submitted for review while publishing blockers remain. Resolve the blockers and generate a valid replacement plan.",
                        HttpStatus.CONFLICT),
        SEAT_HOLD_NOT_FOUND(2140,
                        "Seat hold was not found for this showtime.", HttpStatus.NOT_FOUND),
        SEAT_HOLD_OWNER_MISMATCH(2141,
                        "This seat hold belongs to another account.", HttpStatus.FORBIDDEN),
        SEAT_HOLD_ALREADY_SOLD(2142,
                        "Sold seats cannot be released through the temporary-hold endpoint.",
                        HttpStatus.CONFLICT),
        SEAT_HOLD_RATE_LIMITED(2143,
                        "Too many seat-hold requests. Wait briefly before trying again.",
                        HttpStatus.TOO_MANY_REQUESTS),
        SEAT_HOLD_RETRYABLE_CONFLICT(2144,
                        "Seat inventory is temporarily busy. Refresh availability and retry the same request.",
                        HttpStatus.SERVICE_UNAVAILABLE),
        MAINTENANCE_NOT_FOUND(2145,
                        "Cinema room maintenance record was not found.", HttpStatus.NOT_FOUND),
        MOVIE_SELF_APPROVAL_FORBIDDEN(2146,
                        "The author who prepared this movie draft cannot approve it.", HttpStatus.FORBIDDEN),
        AVAILABILITY_SELF_APPROVAL_FORBIDDEN(2147,
                        "The author who prepared this release plan cannot open it.", HttpStatus.FORBIDDEN),
        SCHEDULE_PLAN_SELF_PUBLISH_FORBIDDEN(2148,
                        "The author who submitted this schedule plan cannot publish it.", HttpStatus.FORBIDDEN),
        AVAILABILITY_REVIEW_NOTE_REQUIRED(2149,
                        "A review note is required when requesting release-plan changes.", HttpStatus.BAD_REQUEST),
        AVAILABILITY_SALES_START_INVALID(2150,
                        "salesStartAt must be on or before showingStartDate.", HttpStatus.BAD_REQUEST);

        int code;
        String message;
        HttpStatusCode statusCode;
}
