server:
  port: 8088

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/database
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

