server:
  port: 8081

spring:
  application:
    name: movie-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5433/movie_db
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

jwt:
  signerKey: 873bcf3b6023c6cfac735831cc01cbd59c6f64c2341050f12e5f0224d7edea62

CLOUDINARY:
  CLOUD_NAME: dzlfgmtbc
  API_KEY: 144287537763843
  API_SECRET: 7kJ1TfEb7kEAVArwaY5jq0ctvlA
