server:
  port: 8081

spring:
  application:
    name: movie-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/movie_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: localhost:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

jwt:
  signerKey: 873bcf3b6023c6cfac735831cc01cbd59c6f64c2341050f12e5f0224d7edea62

tmdb:
  api-key: 4cf6e7ff7b2095ae0d09da1cae2f1606

CLOUDINARY:
  CLOUD_NAME: dzlfgmtbc
  API_KEY: 144287537763843
  API_SECRET: 7kJ1TfEb7kEAVArwaY5jq0ctvlA
