INSERT INTO "type" (type_id, type_name)
VALUES (1, 'Action'),
       (2, 'Adventure'),
       (3, 'Animation'),
       (4, 'Comedy'),
       (5, 'Drama'),
       (6, 'Fantasy'),
       (7, 'Horror'),
       (8, 'Romance'),
       (9, 'Sci-Fi'),
       (10, 'Thriller') ON CONFLICT (type_id) DO NOTHING;

INSERT INTO movie (movie_id,
                   actor,
                   content,
                   director,
                   duration,
                   movie_production_company,
                   version,
                   movie_name_english,
                   movie_name_vn,
                   large_image,
                   small_image,
                   status,
                   create_at,
                   updated_at)
VALUES (1, 'Timothee Chalamet, Zendaya, Rebecca Ferguson',
        'Paul Atreides joins forces with Chani and the Fremen as he seeks revenge against those who destroyed his family, while facing a choice between love and the fate of the known universe.',
        'Denis Villeneuve',
        166,
        'Warner Bros. Pictures',
        '2D Standard',
        'Dune: Part Two',
        'Hanh Tinh Cat: Phan Hai',
        'https://placehold.co/780x1170/1f2937/f8fafc.jpg?text=Dune%3A+Part+Two',
        'https://placehold.co/342x513/1f2937/f8fafc.jpg?text=Dune%3A+Part+Two',
        true,
        NOW(),
        NOW()),
       (2, 'Ryan Reynolds, Hugh Jackman, Emma Corrin',
        'Deadpool teams up with Wolverine on a chaotic mission that could change the fate of their worlds.',
        'Shawn Levy',
        128,
        'Marvel Studios',
        '2D Standard',
        'Deadpool & Wolverine',
        'Deadpool Va Wolverine',
        'https://placehold.co/780x1170/7f1d1d/fef2f2.jpg?text=Deadpool+%26+Wolverine',
        'https://placehold.co/342x513/7f1d1d/fef2f2.jpg?text=Deadpool+%26+Wolverine',
        true,
        NOW(),
        NOW()),
       (3, 'Anya Taylor-Joy, Chris Hemsworth, Tom Burke',
        'Young Furiosa is taken from the Green Place and must survive the wasteland while searching for a way back home.',
        'George Miller',
        148,
        'Warner Bros. Pictures',
        '2D Standard',
        'Furiosa: A Mad Max Saga',
        'Furiosa: Cau Chuyen Tu Max Dien',
        'https://placehold.co/780x1170/78350f/fff7ed.jpg?text=Furiosa',
        'https://placehold.co/342x513/78350f/fff7ed.jpg?text=Furiosa',
        true,
        NOW(),
        NOW()),
       (4, 'Amy Poehler, Maya Hawke, Kensington Tallman',
        'Riley enters her teenage years and faces new emotions that shake up the balance inside her mind.',
        'Kelsey Mann',
        96,
        'Pixar Animation Studios',
        '2D Standard',
        'Inside Out 2',
        'Nhung Manh Ghep Cam Xuc 2',
        'https://placehold.co/780x1170/1e3a8a/eff6ff.jpg?text=Inside+Out+2',
        'https://placehold.co/342x513/1e3a8a/eff6ff.jpg?text=Inside+Out+2',
        true,
        NOW(),
        NOW()),
       (5, 'Kirsten Dunst, Wagner Moura, Cailee Spaeny',
        'A group of journalists travel across a divided America during a near-future civil conflict.',
        'Alex Garland',
        109,
        'A24',
        '2D Standard',
        'Civil War',
        'Noi Chien',
        'https://placehold.co/780x1170/374151/f9fafb.jpg?text=Civil+War',
        'https://placehold.co/342x513/374151/f9fafb.jpg?text=Civil+War',
        true,
        NOW(),
        NOW()),
       (6, 'Steve Carell, Kristen Wiig, Will Ferrell',
        'Gru, Lucy, Margo, Edith, and Agnes welcome a new member to the family, Gru Jr., who is intent on tormenting his dad.',
        'Chris Renaud',
        94,
        'Universal Pictures',
        '2D Standard',
        'Despicable Me 4',
        'Ke Trom Mat Trang 4',
        'https://placehold.co/780x1170/facc15/111827.jpg?text=Despicable+Me+4',
        'https://placehold.co/342x513/facc15/111827.jpg?text=Despicable+Me+4',
        true,
        NOW(),
        NOW()),
       (7, 'Lupita Nyong''o, Joseph Quinn, Alex Wolff',
        'A woman named Sam finds herself trapped in New York City during the early stages of an invasion by alien creatures.',
        'Michael Sarnoski',
        99,
        'Paramount Pictures',
        '2D Standard',
        'A Quiet Place: Day One',
        'Vung Dat Cam Lang: Ngay Mot',
        'https://placehold.co/780x1170/111827/f9fafb.jpg?text=A+Quiet+Place',
        'https://placehold.co/342x513/111827/f9fafb.jpg?text=A+Quiet+Place',
        true,
        NOW(),
        NOW()),
       (8, 'Will Smith, Martin Lawrence, Vanessa Hudgens',
        'When their late captain is accused of corruption, Miami detectives Mike Lowrey and Marcus Burnett fight to clear his name.',
        'Adil El Arbi, Bilall Fallah',
        115,
        'Columbia Pictures',
        '2D Standard',
        'Bad Boys: Ride or Die',
        'Nhung Ga Trai Hu: Choi Den Cung',
        'https://placehold.co/780x1170/0f766e/ecfeff.jpg?text=Bad+Boys',
        'https://placehold.co/342x513/0f766e/ecfeff.jpg?text=Bad+Boys',
        true,
        NOW(),
        NOW()),
       (9, 'Daisy Edgar-Jones, Glen Powell, Anthony Ramos',
        'An update to the 1996 film ''Twister'', which centered on a pair of storm chasers who risk their lives in an attempt to test an experimental weather alert system.',
        'Lee Isaac Chung',
        122,
        'Universal Pictures',
        '2D Standard',
        'Twisters',
        'Loc Xoay Tu Than',
        'https://placehold.co/780x1170/475569/f8fafc.jpg?text=Twisters',
        'https://placehold.co/342x513/475569/f8fafc.jpg?text=Twisters',
        true,
        NOW(),
        NOW()),
       (10, 'Chris Pratt, Samuel L. Jackson, Hannah Waddingham',
        'After an unexpected reunion with his long-lost father, Garfield and Odie are forced into joining a high-stakes heist.',
        'Mark Dindal',
        101,
        'Columbia Pictures',
        '2D Standard',
        'The Garfield Movie',
        'Phim Garfield',
        'https://placehold.co/780x1170/f97316/fff7ed.jpg?text=Garfield',
        'https://placehold.co/342x513/f97316/fff7ed.jpg?text=Garfield',
        true,
        NOW(),
        NOW()),
       (11, 'Owen Teague, Freya Allan, Kevin Durand',
        'Many years after the reign of Caesar, a young ape goes on a journey that will lead him to question everything he has been taught about the past.',
        'Wes Ball',
        145,
        '20th Century Studios',
        '2D Standard',
        'Kingdom of the Planet of the Apes',
        'Hanh Tinh Khi: Vuong Quoc Moi',
        'https://placehold.co/780x1170/334155/f8fafc.jpg?text=Planet+of+the+Apes',
        'https://placehold.co/342x513/334155/f8fafc.jpg?text=Planet+of+the+Apes',
        true,
        NOW(),
        NOW()),
       (12, 'Rebecca Hall, Brian Tyree Henry, Dan Stevens',
        'Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins.',
        'Adam Wingard',
        115,
        'Legendary Pictures',
        '3D IMAX',
        'Godzilla x Kong: The New Empire',
        'Godzilla x Kong: De Che Moi',
        'https://placehold.co/780x1170/064e3b/ecfdf5.jpg?text=Godzilla+x+Kong',
        'https://placehold.co/342x513/064e3b/ecfdf5.jpg?text=Godzilla+x+Kong',
        true,
        NOW(),
        NOW()),
       (13, 'Jack Black, Awkwafina, Viola Davis',
        'Po must train a new Dragon Warrior while facing a shapeshifting sorceress Chameleon.',
        'Mike Mitchell',
        94,
        'DreamWorks Animation',
        '2D Standard',
        'Kung Fu Panda 4',
        'Kung Fu Panda 4',
        'https://placehold.co/780x1170/166534/f0fdf4.jpg?text=Kung+Fu+Panda+4',
        'https://placehold.co/342x513/166534/f0fdf4.jpg?text=Kung+Fu+Panda+4',
        true,
        NOW(),
        NOW()),
       (14, 'Shameik Moore, Hailee Steinfeld, Oscar Isaac',
        'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
        'Joaquim Dos Santos, Kemp Powers',
        140,
        'Sony Pictures',
        '2D Standard',
        'Spider-Man: Across the Spider-Verse',
        'Nguoi Nhen: Du Hanh Vu Tru Nhen',
        'https://placehold.co/780x1170/7c3aed/f5f3ff.jpg?text=Spider-Verse',
        'https://placehold.co/342x513/7c3aed/f5f3ff.jpg?text=Spider-Verse',
        true,
        NOW(),
        NOW()),
       (15, 'Cillian Murphy, Emily Blunt, Matt Damon',
        'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
        'Christopher Nolan',
        180,
        'Universal Pictures',
        '2D Standard',
        'Oppenheimer',
        'Oppenheimer',
        'https://placehold.co/780x1170/27272a/f4f4f5.jpg?text=Oppenheimer',
        'https://placehold.co/342x513/27272a/f4f4f5.jpg?text=Oppenheimer',
        true,
        NOW(),
        NOW()),
       (16, 'Margot Robbie, Ryan Gosling, America Ferrera',
        'Barbie suffers a crisis that leads her to question her world and her existence.',
        'Greta Gerwig',
        114,
        'Warner Bros. Pictures',
        '2D Standard',
        'Barbie',
        'Barbie',
        'https://placehold.co/780x1170/be185d/fdf2f8.jpg?text=Barbie',
        'https://placehold.co/342x513/be185d/fdf2f8.jpg?text=Barbie',
        true,
        NOW(),
        NOW()),
       (17, 'Timothee Chalamet, Rebecca Ferguson, Oscar Isaac',
        'Feature adaptation of Frank Herbert''s science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset in the galaxy.',
        'Denis Villeneuve',
        155,
        'Warner Bros. Pictures',
        '2D Standard',
        'Dune',
        'Hanh Tinh Cat',
        'https://placehold.co/780x1170/92400e/fffbeb.jpg?text=Dune',
        'https://placehold.co/342x513/92400e/fffbeb.jpg?text=Dune',
        true,
        NOW(),
        NOW()),
       (18, 'Robert Pattinson, Zoe Kravitz, Jeffrey Wright',
        'Batman ventures into Gotham City''s underworld when a sadistic killer leaves behind a trail of cryptic clues.',
        'Matt Reeves',
        176,
        'Warner Bros. Pictures',
        '2D Standard',
        'The Batman',
        'Nguoi Doi',
        'https://placehold.co/780x1170/020617/e2e8f0.jpg?text=The+Batman',
        'https://placehold.co/342x513/020617/e2e8f0.jpg?text=The+Batman',
        true,
        NOW(),
        NOW()),
       (19, 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
        'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.',
        'Christopher Nolan',
        169,
        'Paramount Pictures',
        '2D Standard',
        'Interstellar',
        'Ho Den Vu Tru',
        'https://placehold.co/780x1170/312e81/e0e7ff.jpg?text=Interstellar',
        'https://placehold.co/342x513/312e81/e0e7ff.jpg?text=Interstellar',
        true,
        NOW(),
        NOW()),
       (20, 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
        'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
        'Christopher Nolan',
        148,
        'Warner Bros. Pictures',
        '2D Standard',
        'Inception',
        'Ke Danh Cap Giac Mo',
        'https://placehold.co/780x1170/1e40af/dbeafe.jpg?text=Inception',
        'https://placehold.co/342x513/1e40af/dbeafe.jpg?text=Inception',
        true,
        NOW(),
        NOW()) ON CONFLICT (movie_id) DO UPDATE
SET large_image = EXCLUDED.large_image,
    small_image = EXCLUDED.small_image,
    updated_at = NOW();

INSERT INTO movie_movie_types (movies_movie_id, movie_types_type_id)
VALUES (1, 1),
       (1, 2),
       (1, 5),
       (1, 9),
       (2, 1),
       (2, 4),
       (2, 9),
       (3, 1),
       (3, 2),
       (3, 9),
       (4, 3),
       (4, 4),
       (4, 5),
       (5, 1),
       (5, 5),
       (5, 10),
       (6, 3),
       (6, 4),
       (7, 7),
       (7, 9),
       (7, 10),
       (8, 1),
       (8, 4),
       (9, 1),
       (9, 2),
       (9, 5),
       (10, 3),
       (10, 4),
       (11, 1),
       (11, 2),
       (11, 9),
       (12, 1),
       (12, 2),
       (12, 9),
       (13, 1),
       (13, 3),
       (13, 4),
       (14, 1),
       (14, 2),
       (14, 3),
       (14, 9),
       (15, 5),
       (16, 4),
       (16, 6),
       (17, 2),
       (17, 5),
       (17, 9),
       (18, 1),
       (18, 5),
       (18, 10),
       (19, 2),
       (19, 5),
       (19, 9),
       (20, 1),
       (20, 2),
       (20, 9),
       (20, 10) ON CONFLICT DO NOTHING;

-- Seed Cinema Rooms
INSERT INTO cinema_room (cinema_room_id, cinema_room_name, seat_quantity, status)
VALUES (1, 'Cinema 1 (IMAX)', 120, true),
       (2, 'Cinema 2 (3D)', 80, true),
       (3, 'Cinema 3 (Standard)', 100, true),
       (4, 'Cinema 4 (Standard)', 100, true) ON CONFLICT (cinema_room_id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('"type"', 'type_id'), COALESCE((SELECT MAX(type_id) FROM "type"), 1), true);
SELECT setval(pg_get_serial_sequence('movie', 'movie_id'), COALESCE((SELECT MAX(movie_id) FROM movie), 1), true);
SELECT setval(pg_get_serial_sequence('cinema_room', 'cinema_room_id'), COALESCE((SELECT MAX(cinema_room_id) FROM cinema_room), 1), true);
