INSERT INTO "type" (type_id, type_name)
VALUES (1, 'Action'),
       (2, 'Adventure'),
       (3, 'Animation'),
       (4, 'Comedy'),
       (5, 'Drama'),
       (6, 'Fantasy'),
       (7, 'Horror'),
       (8, 'Romance'),
       (9, 'Sci-Fi'),
       (10, 'Thriller') ON CONFLICT (type_id) DO NOTHING;

INSERT INTO movie (movie_id,
                   actor,
                   content,
                   director,
                   duration,
                   movie_production_company,
                   version,
                   movie_name_english,
                   movie_name_vn,
                   large_image,
                   small_image,
                   status,
                   create_at,
                   updated_at)
VALUES (1, 'Timothee Chalamet, Zendaya, Rebecca Ferguson',
        'Paul Atreides joins forces with Chani and the Fremen as he seeks revenge against those who destroyed his family, while facing a choice between love and the fate of the known universe.',
        'Denis Villeneuve',
        166,
        'Warner Bros. Pictures',
        '2D Standard',
        'Dune: Part Two',
        'Hanh Tinh Cat: Phan Hai',
        'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        'https://image.tmdb.org/t/p/w342/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        true,
        NOW(),
        NOW()),
       (2, 'Ryan Reynolds, Hugh Jackman, Emma Corrin',
        'Deadpool teams up with Wolverine on a chaotic mission that could change the fate of their worlds.',
        'Shawn Levy',
        128,
        'Marvel Studios',
        '2D Standard',
        'Deadpool & Wolverine',
        'Deadpool Va Wolverine',
        'https://image.tmdb.org/t/p/w780/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        'https://image.tmdb.org/t/p/w342/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        true,
        NOW(),
        NOW()),
       (3, 'Anya Taylor-Joy, Chris Hemsworth, Tom Burke',
        'Young Furiosa is taken from the Green Place and must survive the wasteland while searching for a way back home.',
        'George Miller',
        148,
        'Warner Bros. Pictures',
        '2D Standard',
        'Furiosa: A Mad Max Saga',
        'Furiosa: Cau Chuyen Tu Max Dien',
        'https://image.tmdb.org/t/p/w780/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
        'https://image.tmdb.org/t/p/w342/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
        true,
        NOW(),
        NOW()),
       (4, 'Amy Poehler, Maya Hawke, Kensington Tallman',
        'Riley enters her teenage years and faces new emotions that shake up the balance inside her mind.',
        'Kelsey Mann',
        96,
        'Pixar Animation Studios',
        '2D Standard',
        'Inside Out 2',
        'Nhung Manh Ghep Cam Xuc 2',
        'https://image.tmdb.org/t/p/w780/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
        'https://image.tmdb.org/t/p/w342/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
        true,
        NOW(),
        NOW()),
       (5, 'Kirsten Dunst, Wagner Moura, Cailee Spaeny',
        'A group of journalists travel across a divided America during a near-future civil conflict.',
        'Alex Garland',
        109,
        'A24',
        '2D Standard',
        'Civil War',
        'Noi Chien',
        'https://image.tmdb.org/t/p/w780/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
        'https://image.tmdb.org/t/p/w342/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
        true,
        NOW(),
        NOW()) ON CONFLICT (movie_id) DO NOTHING;

INSERT INTO movie_movie_types (movies_movie_id, movie_types_type_id)
VALUES (1, 1),
       (1, 2),
       (1, 5),
       (1, 9),
       (2, 1),
       (2, 4),
       (2, 9),
       (3, 1),
       (3, 2),
       (3, 9),
       (4, 3),
       (4, 4),
       (4, 5),
       (5, 1),
       (5, 5),
       (5, 10) ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('"type"', 'type_id'), COALESCE((SELECT MAX(type_id) FROM "type"), 1), true);
SELECT setval(pg_get_serial_sequence('movie', 'movie_id'), COALESCE((SELECT MAX(movie_id) FROM movie), 1), true);
