INSERT INTO "type" (type_id, type_name)
VALUES (1, 'Action'),
       (2, 'Adventure'),
       (3, 'Animation'),
       (4, 'Comedy'),
       (5, 'Drama'),
       (6, 'Fantasy'),
       (7, 'Horror'),
       (8, 'Romance'),
       (9, 'Sci-Fi'),
       (10, 'Thriller') ON CONFLICT (type_id) DO NOTHING;

INSERT INTO movie (movie_id,
                   actor,
                   content,
                   director,
                   duration,
                   movie_production_company,
                   version,
                   movie_name_english,
                   movie_name_vn,
                   large_image,
                   small_image,
                   status,
                   create_at,
                   updated_at)
VALUES (1, 'Timothee Chalamet, Zendaya, Rebecca Ferguson',
        'Paul Atreides joins forces with Chani and the Fremen as he seeks revenge against those who destroyed his family, while facing a choice between love and the fate of the known universe.',
        'Denis Villeneuve',
        166,
        'Warner Bros. Pictures',
        '2D Standard',
        'Dune: Part Two',
        'Hanh Tinh Cat: Phan Hai',
        'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        'https://image.tmdb.org/t/p/w342/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        true,
        NOW(),
        NOW()),
       (2, 'Ryan Reynolds, Hugh Jackman, Emma Corrin',
        'Deadpool teams up with Wolverine on a chaotic mission that could change the fate of their worlds.',
        'Shawn Levy',
        128,
        'Marvel Studios',
        '2D Standard',
        'Deadpool & Wolverine',
        'Deadpool Va Wolverine',
        'https://image.tmdb.org/t/p/w780/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        'https://image.tmdb.org/t/p/w342/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        true,
        NOW(),
        NOW()),
       (3, 'Anya Taylor-Joy, Chris Hemsworth, Tom Burke',
        'Young Furiosa is taken from the Green Place and must survive the wasteland while searching for a way back home.',
        'George Miller',
        148,
        'Warner Bros. Pictures',
        '2D Standard',
        'Furiosa: A Mad Max Saga',
        'Furiosa: Cau Chuyen Tu Max Dien',
        'https://image.tmdb.org/t/p/w780/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
        'https://image.tmdb.org/t/p/w342/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
        true,
        NOW(),
        NOW()),
       (4, 'Amy Poehler, Maya Hawke, Kensington Tallman',
        'Riley enters her teenage years and faces new emotions that shake up the balance inside her mind.',
        'Kelsey Mann',
        96,
        'Pixar Animation Studios',
        '2D Standard',
        'Inside Out 2',
        'Nhung Manh Ghep Cam Xuc 2',
        'https://image.tmdb.org/t/p/w780/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
        'https://image.tmdb.org/t/p/w342/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
        true,
        NOW(),
        NOW()),
       (5, 'Kirsten Dunst, Wagner Moura, Cailee Spaeny',
        'A group of journalists travel across a divided America during a near-future civil conflict.',
        'Alex Garland',
        109,
        'A24',
        '2D Standard',
        'Civil War',
        'Noi Chien',
        'https://image.tmdb.org/t/p/w780/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
        'https://image.tmdb.org/t/p/w342/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
        true,
        NOW(),
        NOW()),
       (6, 'Cillian Murphy, Emily Blunt, Matt Damon',
        'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
        'Christopher Nolan',
        180,
        'Universal Pictures',
        '2D Standard',
        'Oppenheimer',
        'Oppenheimer',
        'https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        'https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        true,
        NOW(),
        NOW()),
       (7, 'Margot Robbie, Ryan Gosling, America Ferrera',
        'Barbie suffers a crisis that leads her to question her world and her existence.',
        'Greta Gerwig',
        114,
        'Warner Bros. Pictures',
        '2D Standard',
        'Barbie',
        'Barbie',
        'https://image.tmdb.org/t/p/w780/sO3V9AgFsdo9jzf8th4HQiOjGJA.jpg',
        'https://image.tmdb.org/t/p/w342/sO3V9AgFsdo9jzf8th4HQiOjGJA.jpg',
        true,
        NOW(),
        NOW()),
       (8, 'Shameik Moore, Hailee Steinfeld, Oscar Isaac',
        'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
        'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
        140,
        'Sony Pictures',
        '2D Standard',
        'Spider-Man: Across the Spider-Verse',
        'Nguoi Nhen: Du Hanh Vu Tru Nhen',
        'https://image.tmdb.org/t/p/w780/paM6UdMgXuXyAK0jhGfV07o3lRW.jpg',
        'https://image.tmdb.org/t/p/w342/paM6UdMgXuXyAK0jhGfV07o3lRW.jpg',
        true,
        NOW(),
        NOW()),
       (9, 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
        'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.',
        'Christopher Nolan',
        169,
        'Paramount Pictures',
        '2D Standard',
        'Interstellar',
        'Ho Den Tu Than',
        'https://image.tmdb.org/t/p/w780/if4TI9LbqNIrzkoOgWjX5PZYDYe.jpg',
        'https://image.tmdb.org/t/p/w342/if4TI9LbqNIrzkoOgWjX5PZYDYe.jpg',
        true,
        NOW(),
        NOW()),
       (10, 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
        'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
        'Christopher Nolan',
        148,
        'Warner Bros. Pictures',
        '2D Standard',
        'Inception',
        'Ke Danh Cap Giac Mo',
        'https://image.tmdb.org/t/p/w780/eBtqGWtR5KUiNl6OXHLR3ri6nVm.jpg',
        'https://image.tmdb.org/t/p/w342/eBtqGWtR5KUiNl6OXHLR3ri6nVm.jpg',
        true,
        NOW(),
        NOW()),
       (11, 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
        'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na''vi race to protect their home.',
        'James Cameron',
        192,
        '20th Century Studios',
        '3D Standard',
        'Avatar: The Way of Water',
        'Avatar: Dong Chay Cua Nuoc',
        'https://image.tmdb.org/t/p/w780/luCqqHf10eQuGAYFO3U7JEqT4XC.jpg',
        'https://image.tmdb.org/t/p/w342/luCqqHf10eQuGAYFO3U7JEqT4XC.jpg',
        true,
        NOW(),
        NOW()),
       (12, 'Chris Pratt, Zoe Saldana, Dave Bautista',
        'Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.',
        'James Gunn',
        150,
        'Marvel Studios',
        '2D Standard',
        'Guardians of the Galaxy Vol. 3',
        'Ve Binh Dai Ngan Ha 3',
        'https://image.tmdb.org/t/p/w780/Ak5hAxorxMpxKoVw5e3kGfxs7sY.jpg',
        'https://image.tmdb.org/t/p/w342/Ak5hAxorxMpxKoVw5e3kGfxs7sY.jpg',
        true,
        NOW(),
        NOW()),
       (13, 'Robert Pattinson, Zoe Kravitz, Jeffrey Wright',
        'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city''s hidden corruption and question his family''s involvement.',
        'Matt Reeves',
        176,
        'Warner Bros. Pictures',
        '2D Standard',
        'The Batman',
        'The Batman',
        'https://image.tmdb.org/t/p/w780/nMp4tu8XuVG3CSWdXTFiHLdngnc.jpg',
        'https://image.tmdb.org/t/p/w342/nMp4tu8XuVG3CSWdXTFiHLdngnc.jpg',
        true,
        NOW(),
        NOW()),
       (14, 'Tom Cruise, Miles Teller, Jennifer Connelly',
        'After thirty years of service as one of the Navy''s top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.',
        'Joseph Kosinski',
        130,
        'Paramount Pictures',
        '2D Standard',
        'Top Gun: Maverick',
        'Phi Cong Sieu Dang Maverick',
        'https://image.tmdb.org/t/p/w780/yuY9mNG8EgYBwDZKH4RFJHRoAUp.jpg',
        'https://image.tmdb.org/t/p/w342/yuY9mNG8EgYBwDZKH4RFJHRoAUp.jpg',
        true,
        NOW(),
        NOW()),
       (15, 'Keanu Reeves, Donnie Yen, Bill Skarsgard',
        'John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
        'Chad Stahelski',
        169,
        'Lionsgate',
        '2D Standard',
        'John Wick: Chapter 4',
        'Sat Thu John Wick 4',
        'https://image.tmdb.org/t/p/w780/dCuJH7UsWOzNrXUzPiGwmcwT8sk.jpg',
        'https://image.tmdb.org/t/p/w342/dCuJH7UsWOzNrXUzPiGwmcwT8sk.jpg',
        true,
        NOW(),
        NOW()),
       (16, 'Michelle Yeoh, Stephanie Hsu, Ke Huy Quan',
        'A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.',
        'Daniel Kwan, Daniel Scheinert',
        139,
        'A24',
        '2D Standard',
        'Everything Everywhere All at Once',
        'Cuoc Chien Da Vu Tru',
        'https://image.tmdb.org/t/p/w780/p7fgHiFZJaJkbWeQ73rmjDfQfU4.jpg',
        'https://image.tmdb.org/t/p/w342/p7fgHiFZJaJkbWeQ73rmjDfQfU4.jpg',
        true,
        NOW(),
        NOW()),
       (17, 'Timothee Chalamet, Rebecca Ferguson, Oscar Isaac',
        'A noble family becomes embroiled in a war for control over the galaxy''s most valuable asset while its heir becomes plagued by visions of a dark future.',
        'Denis Villeneuve',
        155,
        'Warner Bros. Pictures',
        '2D Standard',
        'Dune',
        'Hanh Tinh Cat',
        'https://image.tmdb.org/t/p/w780/kZpP3t5wxOlHscZiDP3LuhuvkiI.jpg',
        'https://image.tmdb.org/t/p/w342/kZpP3t5wxOlHscZiDP3LuhuvkiI.jpg',
        true,
        NOW(),
        NOW()),
       (18, 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
        'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
        'Ridley Scott',
        155,
        'DreamWorks Pictures',
        '2D Standard',
        'Gladiator',
        'Vo Si Giac Dau',
        'https://image.tmdb.org/t/p/w780/usBP3JEXW7iyDfpSfgYFCncg1NA.jpg',
        'https://image.tmdb.org/t/p/w342/usBP3JEXW7iyDfpSfgYFCncg1NA.jpg',
        true,
        NOW(),
        NOW()),
       (19, 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
        'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
        'Lana Wachowski, Lilly Wachowski',
        136,
        'Warner Bros. Pictures',
        '2D Standard',
        'The Matrix',
        'Ma Tran',
        'https://image.tmdb.org/t/p/w780/fE7S6EwaBgRQeqKoDVFoImMmAF4.jpg',
        'https://image.tmdb.org/t/p/w342/fE7S6EwaBgRQeqKoDVFoImMmAF4.jpg',
        true,
        NOW(),
        NOW()),
       (20, 'Daniel Craig, Chris Evans, Ana de Armas',
        'A detective investigates the death of a patriarch of an eccentric, combative family.',
        'Rian Johnson',
        130,
        'Lionsgate',
        '2D Standard',
        'Knives Out',
        'Ke Dam Sau',
        'https://image.tmdb.org/t/p/w780/v0HkE9nxYUtwHpXzXx1uoSLdeW6.jpg',
        'https://image.tmdb.org/t/p/w342/v0HkE9nxYUtwHpXzXx1uoSLdeW6.jpg',
        true,
        NOW(),
        NOW())
ON CONFLICT (movie_id) DO UPDATE SET
    movie_name_english = EXCLUDED.movie_name_english,
    movie_name_vn = EXCLUDED.movie_name_vn,
    actor = EXCLUDED.actor,
    content = EXCLUDED.content,
    director = EXCLUDED.director,
    duration = EXCLUDED.duration,
    movie_production_company = EXCLUDED.movie_production_company,
    version = EXCLUDED.version,
    large_image = EXCLUDED.large_image,
    small_image = EXCLUDED.small_image,
    status = EXCLUDED.status,
    updated_at = NOW();


-- Clean up and re-insert movie-type mappings to prevent duplicates on restart
DELETE FROM movie_movie_types;

INSERT INTO movie_movie_types (movies_movie_id, movie_types_type_id)
VALUES (1, 1),
       (1, 2),
       (1, 5),
       (1, 9),
       (2, 1),
       (2, 4),
       (2, 9),
       (3, 1),
       (3, 2),
       (3, 9),
       (4, 3),
       (4, 4),
       (4, 5),
       (5, 1),
       (5, 5),
       (5, 10),
       (6, 5),
       (6, 10),
       (7, 4),
       (7, 6),
       (7, 2),
       (8, 3),
       (8, 1),
       (8, 2),
       (8, 9),
       (9, 9),
       (9, 5),
       (9, 2),
       (10, 1),
       (10, 9),
       (10, 10),
       (11, 1),
       (11, 2),
       (11, 9),
       (12, 1),
       (12, 2),
       (12, 4),
       (12, 9),
       (13, 1),
       (13, 10),
       (13, 5),
       (14, 1),
       (14, 5),
       (15, 1),
       (15, 10),
       (16, 1),
       (16, 4),
       (16, 9),
       (16, 2),
       (17, 1),
       (17, 2),
       (17, 9),
       (18, 1),
       (18, 5),
       (18, 2),
       (19, 1),
       (19, 9),
       (20, 4),
       (20, 10),
       (20, 5);

SELECT setval(pg_get_serial_sequence('"type"', 'type_id'), COALESCE((SELECT MAX(type_id) FROM "type"), 1), true);
SELECT setval(pg_get_serial_sequence('movie', 'movie_id'), COALESCE((SELECT MAX(movie_id) FROM movie), 1), true);

-- Seed Cinema Rooms (required for Showtime and Booking flow testing)
INSERT INTO cinema_room (cinema_room_id, cinema_room_name, seat_quantity, status)
VALUES (1, 'Cinema 1 (IMAX)', 120, true),
       (2, 'Cinema 2 (3D)', 80, true),
       (3, 'Cinema 3 (Standard)', 100, true),
       (4, 'Cinema 4 (Standard)', 100, true)
ON CONFLICT (cinema_room_id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('cinema_room', 'cinema_room_id'), COALESCE((SELECT MAX(cinema_room_id) FROM cinema_room), 1), true);
